
export interface Recipe {
  id: string;
  title: string;
  description: string;
  image: string;
  category: string;
  prepTime: string;
  cookTime: string;
  totalTime: string;
  servings: number;
  calories: number;
  ingredients: string[];
  instructions: string[];
  notes: string;
  tags: string[];
}

export const recipes: Recipe[] = [
  // Breakfast Recipes (10)
  {
    id: "1",
    title: "Avocado Toast with Poached Egg",
    description: "A simple yet delicious breakfast that's both nutritious and satisfying.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80",
    category: "Breakfast",
    prepTime: "5 minutes",
    cookTime: "5 minutes",
    totalTime: "10 minutes",
    servings: 1,
    calories: 320,
    ingredients: [
      "1 slice whole grain bread",
      "1/2 ripe avocado",
      "1 egg",
      "1 tablespoon vinegar",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh herbs like chives or cilantro (optional)"
    ],
    instructions: [
      "Toast the bread until golden and crisp.",
      "While bread is toasting, bring a pot of water to a gentle simmer. Add vinegar.",
      "Crack the egg into a small bowl. Create a gentle whirlpool in the water and carefully slide the egg in.",
      "Poach for 3-4 minutes for a runny yolk.",
      "Mash the avocado with a fork and spread onto the toast.",
      "Using a slotted spoon, remove the poached egg and place on top of the avocado.",
      "Season with salt, pepper, and optional toppings."
    ],
    notes: "For extra flavor, try adding a squeeze of lemon juice, a drizzle of olive oil, or everything bagel seasoning.",
    tags: ["breakfast", "avocado", "eggs", "healthy", "quick meals"]
  },
  {
    id: "2",
    title: "Berry Smoothie Bowl",
    description: "A refreshing and nutritious smoothie bowl topped with fresh fruits and granola.",
    image: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=764&q=80",
    category: "Breakfast",
    prepTime: "10 minutes",
    cookTime: "0 minutes",
    totalTime: "10 minutes",
    servings: 1,
    calories: 350,
    ingredients: [
      "1 cup frozen mixed berries",
      "1 frozen banana",
      "1/4 cup Greek yogurt",
      "1/4 cup almond milk (or milk of choice)",
      "1 tablespoon honey or maple syrup (optional)",
      "Toppings: fresh berries, sliced banana, granola, chia seeds, coconut flakes"
    ],
    instructions: [
      "Add frozen berries, banana, Greek yogurt, and almond milk to a blender.",
      "Blend until smooth and creamy. Add more milk if needed, but keep it thick enough to eat with a spoon.",
      "Taste and add honey or maple syrup if desired.",
      "Pour into a bowl and arrange toppings in an attractive pattern.",
      "Serve immediately."
    ],
    notes: "For a vegan version, use plant-based yogurt and maple syrup instead of honey.",
    tags: ["breakfast", "smoothie", "healthy", "berries", "quick meals"]
  },
  {
    id: "b1",
    title: "Fluffy Pancakes with Maple Syrup",
    description: "Classic fluffy pancakes that are perfect for a weekend breakfast treat.",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=780&q=80",
    category: "Breakfast",
    prepTime: "10 minutes",
    cookTime: "15 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 420,
    ingredients: [
      "2 cups all-purpose flour",
      "2 tablespoons sugar",
      "4 teaspoons baking powder",
      "1/2 teaspoon salt",
      "2 eggs",
      "1 1/2 cups milk",
      "4 tablespoons melted butter",
      "1 teaspoon vanilla extract",
      "Maple syrup for serving",
      "Fresh berries (optional)"
    ],
    instructions: [
      "In a large bowl, whisk together flour, sugar, baking powder, and salt.",
      "In another bowl, beat the eggs, then add milk, melted butter, and vanilla.",
      "Pour the wet ingredients into the dry ingredients and stir until just combined. Don't overmix.",
      "Let the batter rest for 5 minutes.",
      "Heat a griddle or non-stick pan over medium heat. Lightly grease with butter.",
      "Pour 1/4 cup of batter for each pancake. Cook until bubbles form on the surface, then flip.",
      "Cook for another 1-2 minutes until golden brown.",
      "Serve warm with maple syrup and fresh berries if desired."
    ],
    notes: "For extra fluffy pancakes, substitute buttermilk for regular milk and add 1/2 teaspoon of baking soda.",
    tags: ["breakfast", "pancakes", "weekend", "family"]
  },
  {
    id: "b2",
    title: "Mediterranean Breakfast Bowl",
    description: "A savory breakfast bowl with Mediterranean flavors - perfect for a nutritious start to your day.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    category: "Breakfast",
    prepTime: "15 minutes",
    cookTime: "10 minutes",
    totalTime: "25 minutes",
    servings: 2,
    calories: 380,
    ingredients: [
      "4 eggs",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, diced",
      "1/2 cup feta cheese, crumbled",
      "1/4 cup Kalamata olives, pitted and sliced",
      "2 tablespoons olive oil",
      "1 tablespoon lemon juice",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste",
      "Fresh parsley for garnish",
      "Whole grain toast (optional)"
    ],
    instructions: [
      "Cook eggs according to your preference (scrambled, fried, or poached).",
      "In a bowl, combine tomatoes, cucumber, feta cheese, and olives.",
      "In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and pepper to make the dressing.",
      "Pour the dressing over the vegetables and toss gently.",
      "Divide the vegetable mixture between two bowls.",
      "Top each bowl with two eggs.",
      "Garnish with fresh parsley and serve with whole grain toast if desired."
    ],
    notes: "Add hummus or avocado for extra creaminess and healthy fats.",
    tags: ["breakfast", "mediterranean", "healthy", "savory", "eggs"]
  },
  {
    id: "b3",
    title: "Banana Oatmeal Muffins",
    description: "Healthy and delicious breakfast muffins made with oats and ripe bananas.",
    image: "https://images.unsplash.com/photo-1620145000681-3c9a75cf0bdd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    category: "Breakfast",
    prepTime: "15 minutes",
    cookTime: "20 minutes",
    totalTime: "35 minutes",
    servings: 12,
    calories: 180,
    ingredients: [
      "2 1/2 cups rolled oats (2 cups ground into flour)",
      "3 ripe bananas, mashed",
      "2 eggs",
      "1/3 cup honey or maple syrup",
      "3/4 cup milk of choice",
      "2 teaspoons baking powder",
      "1/2 teaspoon baking soda",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "1/4 teaspoon salt",
      "1/2 cup chopped walnuts or chocolate chips (optional)"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Line a 12-cup muffin tin with paper liners.",
      "Place 2 cups of oats in a blender or food processor and blend until they reach a flour-like consistency.",
      "In a large bowl, mash the bananas. Add eggs, honey, milk, and vanilla, and whisk until well combined.",
      "In another bowl, mix the oat flour, remaining 1/2 cup rolled oats, baking powder, baking soda, cinnamon, and salt.",
      "Add dry ingredients to wet ingredients and stir until just combined. Fold in walnuts or chocolate chips if using.",
      "Divide batter evenly among muffin cups, filling each about 3/4 full.",
      "Bake for 18-20 minutes until a toothpick inserted in the center comes out clean.",
      "Allow to cool in the pan for 5 minutes, then transfer to a wire rack to cool completely."
    ],
    notes: "Store in an airtight container for up to 3 days or freeze for up to 3 months.",
    tags: ["breakfast", "muffins", "banana", "oats", "make ahead"]
  },
  {
    id: "b4",
    title: "Breakfast Burrito",
    description: "A hearty breakfast burrito filled with scrambled eggs, vegetables, and cheese.",
    image: "https://images.unsplash.com/photo-1584178639036-613ba57e5e0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Breakfast",
    prepTime: "10 minutes",
    cookTime: "15 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 450,
    ingredients: [
      "8 large eggs",
      "1/4 cup milk",
      "1 tablespoon olive oil",
      "1 bell pepper, diced",
      "1 small onion, diced",
      "1 cup black beans, rinsed and drained",
      "1 cup shredded cheddar cheese",
      "4 large flour tortillas",
      "1 avocado, sliced",
      "1/4 cup salsa",
      "2 tablespoons chopped cilantro",
      "Salt and pepper to taste",
      "Hot sauce (optional)"
    ],
    instructions: [
      "In a bowl, whisk together eggs and milk, season with salt and pepper.",
      "Heat olive oil in a large skillet over medium heat. Add bell pepper and onion, and cook until softened, about 5 minutes.",
      "Pour the egg mixture into the skillet with the vegetables. Scramble until eggs are just set.",
      "Stir in black beans and cook for another minute to warm through.",
      "Warm the tortillas according to package instructions.",
      "Place a quarter of the egg mixture in the center of each tortilla. Top with cheese, avocado slices, salsa, and cilantro.",
      "Fold in the sides of the tortilla, then roll up tightly.",
      "Serve immediately with hot sauce if desired."
    ],
    notes: "These can be wrapped in foil and frozen for quick breakfasts. Reheat in a 350°F oven for 15-20 minutes.",
    tags: ["breakfast", "burrito", "eggs", "mexican", "make ahead"]
  },
  {
    id: "b5",
    title: "French Toast with Berries",
    description: "Classic french toast topped with fresh berries and a dusting of powdered sugar.",
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1749&q=80",
    category: "Breakfast",
    prepTime: "10 minutes",
    cookTime: "15 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 380,
    ingredients: [
      "8 slices of brioche or challah bread",
      "4 large eggs",
      "1 cup milk",
      "2 tablespoons sugar",
      "1 teaspoon vanilla extract",
      "1/2 teaspoon cinnamon",
      "Pinch of salt",
      "2 tablespoons butter, for cooking",
      "2 cups mixed berries (strawberries, blueberries, raspberries)",
      "Maple syrup, for serving",
      "Powdered sugar, for dusting"
    ],
    instructions: [
      "In a shallow dish, whisk together eggs, milk, sugar, vanilla, cinnamon, and salt.",
      "Heat a large skillet or griddle over medium heat. Add a bit of butter to coat the surface.",
      "Dip each slice of bread in the egg mixture, allowing it to soak for about 10 seconds on each side.",
      "Cook the bread in the skillet until golden brown, about 3-4 minutes per side.",
      "Meanwhile, if desired, warm some of the berries with a splash of maple syrup in a small saucepan to create a berry compote.",
      "Serve french toast topped with fresh berries, a drizzle of maple syrup, and a dusting of powdered sugar."
    ],
    notes: "For a richer french toast, use half-and-half or cream instead of milk.",
    tags: ["breakfast", "french toast", "berries", "weekend", "family"]
  },
  {
    id: "b6",
    title: "Breakfast Quinoa Bowl",
    description: "A nutritious breakfast bowl with quinoa, fruit, and nuts for sustained energy.",
    image: "https://images.unsplash.com/photo-1546548970-71785318a17b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    category: "Breakfast",
    prepTime: "5 minutes",
    cookTime: "20 minutes",
    totalTime: "25 minutes",
    servings: 2,
    calories: 320,
    ingredients: [
      "1 cup quinoa, rinsed",
      "2 cups milk of choice (or 1 cup milk, 1 cup water)",
      "2 tablespoons maple syrup or honey",
      "1 teaspoon vanilla extract",
      "1/2 teaspoon cinnamon",
      "Pinch of salt",
      "1 apple, diced",
      "1/4 cup dried cranberries",
      "1/4 cup chopped almonds or walnuts",
      "2 tablespoons chia seeds",
      "Additional milk for serving"
    ],
    instructions: [
      "In a medium saucepan, combine quinoa, milk, maple syrup, vanilla, cinnamon, and salt.",
      "Bring to a boil, then reduce heat to low, cover, and simmer for 15-20 minutes until quinoa is tender and most of the liquid is absorbed.",
      "Remove from heat and let stand, covered, for 5 minutes.",
      "Fluff the quinoa with a fork and divide between two bowls.",
      "Top each bowl with diced apple, dried cranberries, nuts, and chia seeds.",
      "Serve with additional milk if desired."
    ],
    notes: "Can be made ahead and reheated. Add toppings just before serving.",
    tags: ["breakfast", "quinoa", "healthy", "grain bowl", "make ahead"]
  },
  {
    id: "b7",
    title: "Egg and Vegetable Breakfast Muffins",
    description: "Portable and protein-packed egg muffins with vegetables - perfect for meal prep.",
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Breakfast",
    prepTime: "15 minutes",
    cookTime: "20 minutes",
    totalTime: "35 minutes",
    servings: 12,
    calories: 120,
    ingredients: [
      "10 large eggs",
      "1/4 cup milk",
      "1 bell pepper, finely diced",
      "1 cup spinach, chopped",
      "1/2 cup cherry tomatoes, quartered",
      "1/4 cup red onion, finely diced",
      "1/2 cup shredded cheese (cheddar or feta)",
      "2 tablespoons fresh herbs (chives, parsley, or basil), chopped",
      "Salt and pepper to taste",
      "Cooking spray"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Grease a 12-cup muffin tin with cooking spray.",
      "In a large bowl, whisk together eggs and milk until well combined. Season with salt and pepper.",
      "Divide the diced vegetables and herbs evenly among the muffin cups.",
      "Pour the egg mixture over the vegetables, filling each cup about 3/4 full.",
      "Sprinkle cheese on top of each muffin.",
      "Bake for 18-20 minutes until eggs are set and slightly puffed.",
      "Allow to cool for a few minutes, then run a knife around the edges to remove the egg muffins.",
      "Serve warm or at room temperature."
    ],
    notes: "These keep well in the refrigerator for up to 4 days or can be frozen for up to 3 months. Reheat in microwave for 30 seconds.",
    tags: ["breakfast", "eggs", "meal prep", "protein", "make ahead"]
  },
  {
    id: "b8",
    title: "Whole Grain Breakfast Porridge",
    description: "A warming, hearty porridge made with multiple whole grains and topped with fruit.",
    image: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1776&q=80",
    category: "Breakfast",
    prepTime: "10 minutes",
    cookTime: "25 minutes",
    totalTime: "35 minutes",
    servings: 4,
    calories: 310,
    ingredients: [
      "1/2 cup steel-cut oats",
      "1/4 cup quinoa, rinsed",
      "1/4 cup millet",
      "3 cups milk of choice (or 2 cups milk, 1 cup water)",
      "2 tablespoons maple syrup or honey",
      "1 teaspoon vanilla extract",
      "1 teaspoon cinnamon",
      "1/4 teaspoon salt",
      "2 ripe pears or apples, diced",
      "1/4 cup chopped toasted pecans",
      "2 tablespoons ground flaxseed",
      "Additional milk and honey for serving"
    ],
    instructions: [
      "In a medium saucepan, combine oats, quinoa, millet, milk, maple syrup, vanilla, cinnamon, and salt.",
      "Bring to a boil, then reduce heat to low and simmer, stirring occasionally, for 20-25 minutes until grains are tender and porridge is creamy.",
      "If porridge becomes too thick, add more milk or water to achieve desired consistency.",
      "Divide porridge between four bowls. Top each with diced fruit, pecans, and ground flaxseed.",
      "Serve with additional milk and honey if desired."
    ],
    notes: "For a quicker cooking time, soak the grains overnight in the milk mixture in the refrigerator.",
    tags: ["breakfast", "porridge", "whole grain", "healthy", "winter"]
  },

  // Lunch Recipes (10)
  {
    id: "l1",
    title: "Mediterranean Chickpea Salad",
    description: "A refreshing and protein-rich salad with Mediterranean flavors, perfect for a light lunch.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Lunch",
    prepTime: "15 minutes",
    cookTime: "0 minutes",
    totalTime: "15 minutes",
    servings: 4,
    calories: 320,
    ingredients: [
      "2 cans (15 oz each) chickpeas, drained and rinsed",
      "1 English cucumber, diced",
      "1 pint cherry tomatoes, halved",
      "1 bell pepper, diced",
      "1/2 red onion, finely diced",
      "1/2 cup Kalamata olives, pitted and sliced",
      "1/2 cup feta cheese, crumbled",
      "1/4 cup fresh parsley, chopped",
      "1/4 cup fresh mint, chopped",
      "3 tablespoons olive oil",
      "2 tablespoons lemon juice",
      "1 tablespoon red wine vinegar",
      "1 clove garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and pepper to taste"
    ],
    instructions: [
      "In a large bowl, combine chickpeas, cucumber, tomatoes, bell pepper, red onion, olives, feta cheese, parsley, and mint.",
      "In a small bowl, whisk together olive oil, lemon juice, red wine vinegar, garlic, oregano, salt, and pepper to make the dressing.",
      "Pour the dressing over the salad and toss gently to combine.",
      "Let sit for at least 10 minutes before serving to allow flavors to meld.",
      "Serve chilled or at room temperature."
    ],
    notes: "For meal prep, keep the dressing separate until ready to serve. This salad keeps well in the refrigerator for up to 3 days.",
    tags: ["lunch", "salad", "mediterranean", "vegetarian", "healthy"]
  },
  {
    id: "l2",
    title: "Turkey Avocado Wrap",
    description: "A satisfying wrap filled with turkey, avocado, and fresh vegetables.",
    image: "https://images.unsplash.com/photo-1558985250-27a406d64cb3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Lunch",
    prepTime: "10 minutes",
    cookTime: "0 minutes",
    totalTime: "10 minutes",
    servings: 2,
    calories: 420,
    ingredients: [
      "2 large whole wheat tortillas",
      "4 tablespoons hummus",
      "6 slices deli turkey breast",
      "1 avocado, sliced",
      "1 cup baby spinach",
      "1/2 cucumber, thinly sliced",
      "1/4 red onion, thinly sliced",
      "2 tablespoons crumbled feta cheese",
      "1 tablespoon olive oil",
      "1 teaspoon lemon juice",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Lay out the tortillas on a clean work surface. Spread 2 tablespoons of hummus on each tortilla.",
      "Layer 3 slices of turkey breast on each tortilla.",
      "Divide the avocado slices, baby spinach, cucumber, and red onion between the two tortillas.",
      "Sprinkle with feta cheese.",
      "Drizzle with olive oil and lemon juice, then season with salt and pepper.",
      "Fold in the sides of the tortilla, then roll up tightly from the bottom.",
      "Cut in half diagonally and serve immediately or wrap in parchment paper for later."
    ],
    notes: "For a vegan version, substitute turkey with roasted vegetables and use vegan hummus and cheese alternatives.",
    tags: ["lunch", "wrap", "turkey", "quick meals", "protein"]
  },
  {
    id: "l3",
    title: "Quinoa Power Bowl",
    description: "A nutritious and filling bowl with quinoa, roasted vegetables, and a tahini dressing.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1760&q=80",
    category: "Lunch",
    prepTime: "15 minutes",
    cookTime: "25 minutes",
    totalTime: "40 minutes",
    servings: 4,
    calories: 380,
    ingredients: [
      "1 cup quinoa, rinsed",
      "2 cups vegetable broth",
      "1 sweet potato, diced",
      "1 red bell pepper, diced",
      "1 zucchini, diced",
      "1 red onion, diced",
      "2 tablespoons olive oil",
      "1 teaspoon cumin",
      "1 teaspoon paprika",
      "1/2 teaspoon garlic powder",
      "Salt and pepper to taste",
      "1 can (15 oz) chickpeas, drained and rinsed",
      "2 cups kale, chopped",
      "1 avocado, sliced",
      "1/4 cup pumpkin seeds",
      "For the tahini dressing:",
      "1/4 cup tahini",
      "2 tablespoons lemon juice",
      "1 tablespoon maple syrup",
      "1 clove garlic, minced",
      "3-4 tablespoons water",
      "Salt to taste"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Line a baking sheet with parchment paper.",
      "Cook quinoa according to package instructions, using vegetable broth instead of water.",
      "In a large bowl, toss sweet potato, bell pepper, zucchini, and red onion with olive oil, cumin, paprika, garlic powder, salt, and pepper.",
      "Spread vegetables on the prepared baking sheet and roast for 20-25 minutes, stirring halfway through, until tender and slightly browned.",
      "Meanwhile, prepare the tahini dressing by whisking together tahini, lemon juice, maple syrup, garlic, water, and salt until smooth.",
      "Massage the chopped kale with a little olive oil and salt for about 1 minute to soften it.",
      "To assemble the bowls, divide the quinoa among four bowls. Top with roasted vegetables, chickpeas, massaged kale, avocado slices, and pumpkin seeds.",
      "Drizzle with tahini dressing and serve."
    ],
    notes: "This is great for meal prep. Store the components separately and assemble when ready to eat.",
    tags: ["lunch", "bowl", "quinoa", "vegetarian", "healthy"]
  },
  {
    id: "l4",
    title: "Tuna Niçoise Salad",
    description: "A classic French salad featuring tuna, eggs, potatoes, and green beans.",
    image: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1364&q=80",
    category: "Lunch",
    prepTime: "20 minutes",
    cookTime: "15 minutes",
    totalTime: "35 minutes",
    servings: 4,
    calories: 420,
    ingredients: [
      "1 pound small red potatoes, halved",
      "8 oz green beans, trimmed",
      "4 large eggs",
      "2 cans (5 oz each) tuna in olive oil, drained",
      "1 head butter lettuce, torn into bite-sized pieces",
      "1 cup cherry tomatoes, halved",
      "1/2 cup Kalamata olives",
      "1/4 cup red onion, thinly sliced",
      "For the dressing:",
      "3 tablespoons olive oil",
      "2 tablespoons red wine vinegar",
      "1 tablespoon Dijon mustard",
      "1 clove garlic, minced",
      "1 teaspoon anchovy paste (optional)",
      "1 tablespoon fresh herbs (parsley, chives, or tarragon), chopped",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Place potatoes in a medium saucepan, cover with cold water, and add a pinch of salt. Bring to a boil and cook until tender, about 10-12 minutes. Drain and let cool slightly.",
      "While potatoes are cooking, bring another pot of water to a boil. Add green beans and cook for 3-4 minutes until crisp-tender. Transfer to an ice bath to stop cooking, then drain.",
      "Place eggs in a saucepan, cover with cold water, and bring to a boil. Once boiling, remove from heat, cover, and let sit for 9 minutes. Transfer to an ice bath, then peel and quarter.",
      "In a small bowl, whisk together all dressing ingredients until well combined.",
      "Arrange lettuce on a large platter or divide among four plates.",
      "Top with potatoes, green beans, tuna, tomatoes, olives, and red onion.",
      "Arrange egg quarters around the salad.",
      "Drizzle with dressing and serve immediately."
    ],
    notes: "Traditional Niçoise salad uses raw vegetables, but blanching the green beans enhances their color and texture.",
    tags: ["lunch", "salad", "french", "tuna", "protein"]
  },
  {
    id: "l5",
    title: "Vegetable Soup with Pesto",
    description: "A hearty vegetable soup topped with fresh pesto for extra flavor.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1742&q=80",
    category: "Lunch",
    prepTime: "15 minutes",
    cookTime: "30 minutes",
    totalTime: "45 minutes",
    servings: 6,
    calories: 250,
    ingredients: [
      "2 tablespoons olive oil",
      "1 onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "2 cloves garlic, minced",
      "1 zucchini, diced",
      "1 yellow squash, diced",
      "1 red bell pepper, diced",
      "1 can (14.5 oz) diced tomatoes",
      "6 cups vegetable broth",
      "1 teaspoon dried thyme",
      "1 teaspoon dried oregano",
      "1 bay leaf",
      "1 can (15 oz) cannellini beans, drained and rinsed",
      "2 cups spinach, chopped",
      "1/2 cup small pasta (like ditalini or orzo)",
      "Salt and pepper to taste",
      "For the pesto:",
      "2 cups fresh basil leaves",
      "1/4 cup pine nuts",
      "1/3 cup grated Parmesan cheese",
      "2 cloves garlic",
      "1/2 cup olive oil",
      "Salt to taste"
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion, carrots, and celery, and sauté for 5 minutes until softened.",
      "Add garlic and cook for 1 minute until fragrant.",
      "Add zucchini, yellow squash, and bell pepper, and cook for 3-4 minutes.",
      "Stir in diced tomatoes, vegetable broth, thyme, oregano, and bay leaf. Bring to a boil.",
      "Add pasta and cook according to package directions, usually 8-10 minutes.",
      "While the soup is cooking, make the pesto: In a food processor, combine basil, pine nuts, Parmesan, and garlic. Pulse until coarsely chopped. With the processor running, slowly add olive oil until smooth. Season with salt.",
      "Add cannellini beans and spinach to the soup. Cook for 2-3 minutes until spinach is wilted.",
      "Remove bay leaf and season with salt and pepper.",
      "Serve soup in bowls, topped with a dollop of fresh pesto."
    ],
    notes: "The soup can be made ahead and refrigerated for up to 3 days. The pasta may absorb liquid, so you might need to add more broth when reheating.",
    tags: ["lunch", "soup", "vegetarian", "healthy", "make ahead"]
  },
  {
    id: "l6",
    title: "Chicken Caesar Wrap",
    description: "A classic Caesar salad wrapped in a tortilla for an easy, portable lunch.",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Lunch",
    prepTime: "15 minutes",
    cookTime: "10 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 450,
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "1 tablespoon olive oil",
      "1 teaspoon Italian seasoning",
      "Salt and pepper to taste",
      "4 large flour tortillas",
      "1/2 cup Caesar dressing",
      "4 cups romaine lettuce, chopped",
      "1/2 cup Parmesan cheese, shaved",
      "1 cup croutons, slightly crushed",
      "1 lemon, cut into wedges (optional)"
    ],
    instructions: [
      "Season chicken breasts with Italian seasoning, salt, and pepper.",
      "Heat olive oil in a skillet over medium-high heat. Cook chicken for 5-6 minutes per side until internal temperature reaches 165°F (74°C).",
      "Remove chicken from pan and let rest for 5 minutes, then slice thinly.",
      "Warm tortillas according to package instructions to make them more pliable.",
      "Spread 2 tablespoons of Caesar dressing on each tortilla.",
      "Layer each tortilla with romaine lettuce, sliced chicken, Parmesan cheese, and croutons.",
      "Fold in the sides of the tortilla, then roll up tightly from the bottom.",
      "Cut each wrap in half diagonally and serve with lemon wedges if desired."
    ],
    notes: "For a shortcut, use rotisserie chicken instead of cooking chicken breasts. For a lower-carb option, use large lettuce leaves instead of tortillas.",
    tags: ["lunch", "wrap", "chicken", "caesar", "quick meals"]
  },
  {
    id: "l7",
    title: "Black Bean and Corn Quesadillas",
    description: "Crispy quesadillas filled with black beans, corn, cheese, and spices.",
    image: "https://images.unsplash.com/photo-1618040996507-91f984aae5a0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1738&q=80",
    category: "Lunch",
    prepTime: "10 minutes",
    cookTime: "15 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 380,
    ingredients: [
      "1 tablespoon olive oil, plus more for cooking",
      "1 small onion, diced",
      "1 bell pepper, diced",
      "2 cloves garlic, minced",
      "1 can (15 oz) black beans, drained and rinsed",
      "1 cup corn kernels (fresh, frozen, or canned)",
      "1 teaspoon cumin",
      "1 teaspoon chili powder",
      "1/2 teaspoon smoked paprika",
      "1/4 teaspoon cayenne pepper (optional)",
      "Salt and pepper to taste",
      "8 medium flour tortillas",
      "2 cups shredded Mexican blend cheese",
      "1/4 cup cilantro, chopped",
      "Salsa, guacamole, and sour cream for serving"
    ],
    instructions: [
      "Heat olive oil in a skillet over medium heat. Add onion and bell pepper, and cook until softened, about 5 minutes.",
      "Add garlic and cook for 1 minute until fragrant.",
      "Stir in black beans, corn, cumin, chili powder, smoked paprika, cayenne (if using), salt, and pepper. Cook for 3-4 minutes, mashing some of the beans with a spoon. Remove from heat and stir in cilantro.",
      "Heat a large skillet or griddle over medium heat. Lightly brush with oil.",
      "Place a tortilla in the skillet. Sprinkle 1/4 cup cheese on half of the tortilla, then top with about 1/3 cup of the bean mixture. Add another 1/4 cup cheese on top, then fold the tortilla in half.",
      "Cook for 2-3 minutes per side until golden brown and crispy, and the cheese is melted.",
      "Repeat with remaining tortillas and filling.",
      "Cut each quesadilla into wedges and serve with salsa, guacamole, and sour cream."
    ],
    notes: "The bean mixture can be made ahead and refrigerated for up to 3 days. For a spicier version, add a diced jalapeño with the bell pepper.",
    tags: ["lunch", "quesadilla", "mexican", "vegetarian", "quick meals"]
  },
  {
    id: "l8",
    title: "Sesame Noodle Salad",
    description: "A refreshing cold noodle salad with vegetables and a flavorful sesame dressing.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Lunch",
    prepTime: "20 minutes",
    cookTime: "10 minutes",
    totalTime: "30 minutes",
    servings: 6,
    calories: 320,
    ingredients: [
      "8 oz soba noodles or whole wheat spaghetti",
      "2 cups red cabbage, thinly sliced",
      "1 red bell pepper, thinly sliced",
      "1 carrot, julienned",
      "1 cucumber, julienned",
      "3 green onions, thinly sliced",
      "1/2 cup cilantro, chopped",
      "1/4 cup roasted peanuts, chopped",
      "1 tablespoon sesame seeds",
      "For the dressing:",
      "3 tablespoons sesame oil",
      "2 tablespoons rice vinegar",
      "2 tablespoons soy sauce",
      "1 tablespoon honey or maple syrup",
      "1 tablespoon ginger, grated",
      "2 cloves garlic, minced",
      "1 tablespoon tahini",
      "1 teaspoon sriracha (optional)"
    ],
    instructions: [
      "Cook noodles according to package instructions. Drain and rinse under cold water to stop cooking.",
      "In a large bowl, combine noodles, cabbage, bell pepper, carrot, cucumber, and green onions.",
      "In a small bowl, whisk together all dressing ingredients until well combined.",
      "Pour dressing over the noodle mixture and toss to coat evenly.",
      "Add cilantro and toss again.",
      "Refrigerate for at least 30 minutes to allow flavors to meld.",
      "Before serving, top with chopped peanuts and sesame seeds."
    ],
    notes: "This salad keeps well in the refrigerator for up to 3 days. Add cooked chicken, tofu, or shrimp for extra protein.",
    tags: ["lunch", "salad", "noodles", "asian", "make ahead"]
  },
  {
    id: "l9",
    title: "Italian Panini",
    description: "A pressed sandwich filled with Italian meats, cheeses, and vegetables.",
    image: "https://images.unsplash.com/photo-1481070414801-51fd732d7184?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1824&q=80",
    category: "Lunch",
    prepTime: "10 minutes",
    cookTime: "5 minutes",
    totalTime: "15 minutes",
    servings: 2,
    calories: 520,
    ingredients: [
      "1 ciabatta loaf or 2 ciabatta rolls",
      "2 tablespoons pesto",
      "2 tablespoons sun-dried tomato spread",
      "4 slices provolone cheese",
      "4 slices salami",
      "4 slices prosciutto",
      "1/2 cup arugula",
      "1/4 cup roasted red peppers, sliced",
      "1/4 red onion, thinly sliced",
      "2 tablespoons olive oil",
      "1 tablespoon balsamic glaze"
    ],
    instructions: [
      "Cut ciabatta in half horizontally. If using a loaf, cut into two portions.",
      "Spread pesto on the bottom half and sun-dried tomato spread on the top half.",
      "Layer provolone cheese, salami, prosciutto, arugula, roasted red peppers, and red onion on the bottom half.",
      "Drizzle with balsamic glaze, then place the top half on the sandwich.",
      "Brush the outside of the sandwich with olive oil.",
      "Heat a panini press or skillet over medium heat.",
      "If using a panini press, place the sandwich in the press and cook for 3-5 minutes until bread is crispy and cheese is melted.",
      "If using a skillet, place the sandwich in the skillet and press down with a heavy pot or pan. Cook for 2-3 minutes per side until golden brown.",
      "Cut the sandwich diagonally and serve hot."
    ],
    notes: "Customize with your favorite Italian meats and cheeses. For a vegetarian version, omit the meats and add grilled vegetables like zucchini and eggplant.",
    tags: ["lunch", "sandwich", "italian", "hot", "quick meals"]
  },
  {
    id: "l10",
    title: "Lentil and Vegetable Soup",
    description: "A hearty and nutritious soup packed with lentils and vegetables.",
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1587&q=80",
    category: "Lunch",
    prepTime: "15 minutes",
    cookTime: "40 minutes",
    totalTime: "55 minutes",
    servings: 6,
    calories: 280,
    ingredients: [
      "2 tablespoons olive oil",
      "1 large onion, diced",
      "2 carrots, diced",
      "2 celery stalks, diced",
      "3 cloves garlic, minced",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1/2 teaspoon red pepper flakes (optional)",
      "1 cup green or brown lentils, rinsed and picked over",
      "1 can (14.5 oz) diced tomatoes",
      "6 cups vegetable broth",
      "2 bay leaves",
      "1 teaspoon dried thyme",
      "2 cups chopped kale or spinach",
      "1 tablespoon lemon juice",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion, carrots, and celery, and sauté for 5 minutes until softened.",
      "Add garlic, cumin, coriander, and red pepper flakes (if using), and cook for 1 minute until fragrant.",
      "Add lentils, diced tomatoes, vegetable broth, bay leaves, and thyme. Bring to a boil.",
      "Reduce heat to low, cover, and simmer for 30-35 minutes until lentils are tender.",
      "Remove bay leaves. Use an immersion blender to partially blend the soup, leaving some texture, or blend 2 cups of soup in a blender and return to the pot.",
      "Stir in kale or spinach and cook for 3-4 minutes until wilted.",
      "Add lemon juice, and season with salt and pepper to taste.",
      "Serve hot, garnished with fresh parsley."
    ],
    notes: "This soup thickens as it sits. When reheating, you may need to add more broth or water to reach desired consistency. Freezes well for up to 3 months.",
    tags: ["lunch", "soup", "lentils", "vegetarian", "healthy", "make ahead"]
  },

  // Dinner Recipes (first 3 from the original data)
  {
    id: "3",
    title: "Vegetable Stir Fry",
    description: "A quick and healthy vegetable stir fry that's perfect for busy weeknights.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    category: "Dinner",
    prepTime: "15 minutes",
    cookTime: "10 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 220,
    ingredients: [
      "2 tablespoons vegetable oil",
      "2 cloves garlic, minced",
      "1 tablespoon ginger, grated",
      "1 bell pepper, sliced",
      "1 carrot, julienned",
      "1 cup broccoli florets",
      "1 cup snap peas",
      "1 cup mushrooms, sliced",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 teaspoon sesame oil",
      "1/4 cup vegetable broth",
      "Sesame seeds and green onions for garnish"
    ],
    instructions: [
      "Heat vegetable oil in a large wok or skillet over high heat.",
      "Add garlic and ginger, stir-fry for 30 seconds until fragrant.",
      "Add carrots and cook for 1 minute.",
      "Add bell pepper, broccoli, snap peas, and mushrooms. Stir-fry for 3-4 minutes until vegetables are crisp-tender.",
      "In a small bowl, mix soy sauce, oyster sauce, sesame oil, and vegetable broth.",
      "Pour sauce over vegetables and toss to coat. Cook for another 1-2 minutes.",
      "Garnish with sesame seeds and sliced green onions before serving."
    ],
    notes: "Serve over rice or noodles for a complete meal. Add tofu, chicken, or beef for extra protein.",
    tags: ["stir fry", "vegetables", "healthy", "quick meals", "vegan"]
  },
  {
    id: "1",
    title: "Creamy Garlic Pasta",
    description: "This creamy garlic pasta is simple to make and packed with flavor. It's the perfect weeknight dinner!",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80",
    category: "Dinner",
    prepTime: "10 minutes",
    cookTime: "20 minutes",
    totalTime: "30 minutes",
    servings: 4,
    calories: 450,
    ingredients: [
      "8 oz fettuccine pasta",
      "2 tablespoons olive oil",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1/2 cup grated parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Cook pasta according to package directions. Reserve 1/2 cup pasta water before draining.",
      "In a large skillet, heat olive oil over medium heat. Add minced garlic and cook until fragrant, about 1 minute.",
      "Pour in the heavy cream and bring to a simmer. Cook for 3-4 minutes until it starts to thicken.",
      "Stir in the parmesan cheese until melted and smooth.",
      "Add the cooked pasta to the sauce and toss to coat. If needed, add reserved pasta water to thin the sauce.",
      "Season with salt and pepper to taste.",
      "Garnish with fresh parsley before serving."
    ],
    notes: "For extra protein, add grilled chicken or shrimp.",
    tags: ["pasta", "italian", "quick meals", "vegetarian"]
  },
  {
    id: "6",
    title: "Homemade Margherita Pizza",
    description: "A classic Italian pizza with fresh tomatoes, mozzarella, and basil.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1469&q=80",
    category: "Dinner",
    prepTime: "30 minutes",
    cookTime: "15 minutes",
    totalTime: "45 minutes",
    servings: 4,
    calories: 290,
    ingredients: [
      "Pizza dough (store-bought or homemade)",
      "1/4 cup tomato sauce",
      "8 oz fresh mozzarella, sliced",
      "2 ripe tomatoes, sliced",
      "Fresh basil leaves",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)"
    ],
    instructions: [
      "Preheat oven to 475°F (245°C). If using a pizza stone, place it in the oven while preheating.",
      "Roll out pizza dough on a floured surface to desired thickness.",
      "Spread tomato sauce evenly over the dough, leaving a small border for the crust.",
      "Arrange mozzarella slices and tomato slices on top.",
      "Sprinkle with salt and pepper.",
      "Transfer pizza to preheated stone or baking sheet.",
      "Bake for 12-15 minutes until crust is golden and cheese is bubbly.",
      "Remove from oven and immediately top with fresh basil leaves and a drizzle of olive oil.",
      "Sprinkle with red pepper flakes if desired before serving."
    ],
    notes: "For the best flavor, use high-quality ingredients, especially the olive oil and tomatoes.",
    tags: ["pizza", "italian", "dinner", "vegetarian"]
  },
  {
    id: "d1",
    title: "Beef and Broccoli Stir Fry",
    description: "A quick and flavorful Asian-inspired dinner with tender beef and crisp broccoli.",
    image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Dinner",
    prepTime: "15 minutes",
    cookTime: "15 minutes",
    totalTime: "30 minutes",
    servings: 4,
    calories: 380,
    ingredients: [
      "1 lb flank steak, thinly sliced against the grain",
      "2 tablespoons cornstarch",
      "3 tablespoons vegetable oil, divided",
      "4 cups broccoli florets",
      "1 red bell pepper, sliced",
      "1 onion, sliced",
      "3 cloves garlic, minced",
      "1 tablespoon ginger, grated",
      "For the sauce:",
      "1/2 cup beef broth",
      "1/4 cup soy sauce",
      "2 tablespoons oyster sauce",
      "1 tablespoon brown sugar",
      "1 teaspoon sesame oil",
      "1 tablespoon cornstarch",
      "Cooked rice for serving",
      "Green onions and sesame seeds for garnish"
    ],
    instructions: [
      "In a bowl, toss sliced beef with 2 tablespoons cornstarch until evenly coated.",
      "In a small bowl, whisk together all sauce ingredients until smooth.",
      "Heat 2 tablespoons oil in a large wok or skillet over high heat. Add beef in a single layer and cook for 1-2 minutes per side until browned. Work in batches if necessary. Remove beef to a plate.",
      "Add remaining 1 tablespoon oil to the wok. Add broccoli, bell pepper, and onion, and stir-fry for 4-5 minutes until vegetables begin to soften.",
      "Add garlic and ginger, and stir-fry for 30 seconds until fragrant.",
      "Return beef to the wok. Pour sauce over everything and stir well.",
      "Cook for 2-3 minutes until sauce thickens and everything is well coated.",
      "Serve over rice, garnished with green onions and sesame seeds."
    ],
    notes: "For extra tender beef, marinate it in 1 tablespoon of baking soda mixed with 1/4 cup water for 30 minutes, then rinse well before cooking.",
    tags: ["dinner", "stir fry", "beef", "asian", "quick meals"]
  },
  {
    id: "d2",
    title: "Baked Salmon with Lemon and Herbs",
    description: "Perfectly baked salmon fillets with a bright lemon and herb flavor.",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Dinner",
    prepTime: "10 minutes",
    cookTime: "15 minutes",
    totalTime: "25 minutes",
    servings: 4,
    calories: 320,
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "2 tablespoons olive oil",
      "2 tablespoons lemon juice",
      "2 cloves garlic, minced",
      "1 tablespoon fresh dill, chopped",
      "1 tablespoon fresh parsley, chopped",
      "1 teaspoon lemon zest",
      "Salt and pepper to taste",
      "Lemon slices for garnish"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper or aluminum foil.",
      "Place salmon fillets on the prepared baking sheet, skin side down.",
      "In a small bowl, mix olive oil, lemon juice, garlic, dill, parsley, and lemon zest.",
      "Spoon the herb mixture over the salmon, making sure to cover each fillet completely.",
      "Season with salt and pepper.",
      "Bake for 12-15 minutes, depending on thickness, until salmon flakes easily with a fork.",
      "Garnish with lemon slices and additional fresh herbs before serving."
    ],
    notes: "For a complete meal, serve with roasted asparagus and quinoa. You can also grill the salmon on a cedar plank for additional flavor.",
    tags: ["dinner", "salmon", "seafood", "healthy", "quick meals"]
  },
  {
    id: "d3",
    title: "Chicken Enchiladas",
    description: "Flavorful chicken enchiladas with a homemade enchilada sauce and melted cheese.",
    image: "https://images.unsplash.com/photo-1600891963935-9e72bf1e28c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1738&q=80",
    category: "Dinner",
    prepTime: "30 minutes",
    cookTime: "25 minutes",
    totalTime: "55 minutes",
    servings: 6,
    calories: 420,
    ingredients: [
      "3 cups cooked chicken, shredded",
      "1 onion, diced",
      "1 bell pepper, diced",
      "2 cloves garlic, minced",
      "1 tablespoon olive oil",
      "1 teaspoon cumin",
      "1 teaspoon chili powder",
      "1/2 teaspoon oregano",
      "1 cup black beans, drained and rinsed",
      "1/2 cup corn kernels",
      "2 cups enchilada sauce, divided",
      "12 small flour or corn tortillas",
      "2 cups shredded Mexican blend cheese",
      "For garnish: cilantro, avocado, sour cream, lime wedges"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Grease a 9x13 inch baking dish.",
      "Heat olive oil in a large skillet over medium heat. Add onion and bell pepper, and cook until softened, about 5 minutes.",
      "Add garlic and cook for 1 minute until fragrant.",
      "Stir in shredded chicken, cumin, chili powder, oregano, black beans, and corn. Cook for 2-3 minutes.",
      "Add 1/2 cup of enchilada sauce to the chicken mixture and stir to combine.",
      "Pour 1/2 cup of enchilada sauce into the bottom of the prepared baking dish.",
      "Warm tortillas according to package instructions to make them more pliable.",
      "Spoon about 1/4 cup of the chicken mixture onto each tortilla. Roll up tightly and place seam side down in the baking dish.",
      "Pour the remaining 1 cup of enchilada sauce over the enchiladas and sprinkle with cheese.",
      "Bake for 20-25 minutes until cheese is melted and bubbly.",
      "Garnish with cilantro, avocado, sour cream, and lime wedges before serving."
    ],
    notes: "You can use rotisserie chicken for a shortcut. Make your own enchilada sauce for even better flavor.",
    tags: ["dinner", "mexican", "chicken", "family meals"]
  },
  {
    id: "d4",
    title: "Eggplant Parmesan",
    description: "A classic Italian dish with layers of breaded eggplant, tomato sauce, and cheese.",
    image: "https://images.unsplash.com/photo-1629115916087-7e8c114a6a21?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1752&q=80",
    category: "Dinner",
    prepTime: "30 minutes",
    cookTime: "40 minutes",
    totalTime: "1 hour 10 minutes",
    servings: 6,
    calories: 380,
    ingredients: [
      "2 large eggplants, sliced into 1/4-inch rounds",
      "2 cups Italian breadcrumbs",
      "1/2 cup grated Parmesan cheese, plus more for layering",
      "3 large eggs, beaten",
      "1/4 cup milk",
      "1/2 cup all-purpose flour",
      "Salt and pepper to taste",
      "Olive oil for frying",
      "3 cups marinara sauce",
      "1 pound mozzarella cheese, sliced",
      "1/4 cup fresh basil, chopped",
      "1/4 teaspoon red pepper flakes (optional)"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Sprinkle eggplant slices with salt and let sit for 30 minutes to draw out moisture. Pat dry with paper towels.",
      "Set up three bowls: one with flour seasoned with salt and pepper, one with eggs beaten with milk, and one with breadcrumbs mixed with 1/2 cup Parmesan cheese.",
      "Dip each eggplant slice in flour, then egg mixture, then breadcrumb mixture, pressing to adhere.",
      "Heat olive oil in a large skillet over medium heat. Working in batches, fry eggplant slices for 2-3 minutes per side until golden brown. Drain on paper towels.",
      "Spread 1/2 cup marinara sauce in the bottom of a 9x13 inch baking dish.",
      "Layer half the eggplant slices, slightly overlapping. Top with half the remaining sauce and half the mozzarella.",
      "Repeat with remaining eggplant, sauce, and mozzarella. Sprinkle with additional Parmesan.",
      "Bake for 35-40 minutes until cheese is bubbly and golden.",
      "Let stand for 10 minutes before serving. Garnish with fresh basil and red pepper flakes if desired."
    ],
    notes: "For a lighter version, roast the eggplant slices in the oven instead of frying. You can also make this ahead and refrigerate before baking.",
    tags: ["dinner", "italian", "vegetarian", "eggplant", "casserole"]
  },
  {
    id: "d5",
    title: "Shrimp Scampi with Linguine",
    description: "Garlicky buttery shrimp served over linguine pasta - a quick and elegant dinner.",
    image: "https://images.unsplash.com/photo-1633797194548-0c3b542c2d1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80",
    category: "Dinner",
    prepTime: "15 minutes",
    cookTime: "15 minutes",
    totalTime: "30 minutes",
    servings: 4,
    calories: 450,
    ingredients: [
      "1 pound linguine pasta",
      "1 1/2 pounds large shrimp, peeled and deveined",
      "4 tablespoons butter",
      "4 tablespoons olive oil",
      "6 cloves garlic, minced",
      "1/2 teaspoon red pepper flakes",
      "1/2 cup dry white wine",
      "1 lemon, juiced and zested",
      "1/4 cup fresh parsley, chopped",
      "Salt and pepper to taste",
      "Grated Parmesan cheese for serving"
    ],
    instructions: [
      "Cook linguine according to package directions. Reserve 1/2 cup pasta water before draining.",
      "Pat shrimp dry and season with salt and pepper.",
      "In a large skillet, heat 2 tablespoons olive oil over medium-high heat. Add shrimp in a single layer and cook for 1-2 minutes per side until pink. Transfer to a plate.",
      "In the same skillet, add remaining olive oil and butter. Once butter is melted, add garlic and red pepper flakes. Cook for 1 minute until fragrant.",
      "Add white wine and lemon juice, and bring to a simmer. Cook for 2-3 minutes until slightly reduced.",
      "Return shrimp to the skillet and add lemon zest and parsley. Toss to coat shrimp in sauce.",
      "Add drained linguine to the skillet and toss to combine. If needed, add reserved pasta water to loosen the sauce.",
      "Serve immediately with grated Parmesan cheese."
    ],
    notes: "For extra flavor, marinate the shrimp in a mixture of olive oil, garlic, and lemon zest for 30 minutes before cooking.",
    tags: ["dinner", "pasta", "shrimp", "seafood", "italian", "quick meals"]
  },
  {
    id: "d6",
    title: "Stuffed Bell Peppers",
    description: "Bell peppers stuffed with a flavorful mixture of rice, ground beef, and vegetables.",
    image: "https://images.unsplash.com/photo-1601006816831-b7f17d31d3a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1752&q=80",
    category: "Dinner",
    prepTime: "20 minutes",
    cookTime: "40 minutes",
    totalTime: "1 hour",
    servings: 6,
    calories: 350,
    ingredients: [
      "6 large bell peppers, tops cut off and seeds removed",
      "1 pound ground beef",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 zucchini, diced",
      "1 cup cooked rice",
      "1 can (14.5 oz) diced tomatoes, drained",
      "1 tablespoon tomato paste",
      "1 teaspoon Italian seasoning",
      "1/2 teaspoon cumin",
      "1/2 cup beef broth",
      "1 cup shredded cheddar cheese, divided",
      "2 tablespoons fresh parsley, chopped",
      "Salt and pepper to taste"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Place bell peppers in a baking dish. If needed, cut a thin slice from the bottom of each pepper so they stand upright.",
      "In a large skillet over medium heat, cook ground beef, breaking it up with a spoon, until no longer pink, about 5-7 minutes. Drain excess fat.",
      "Add onion and garlic to the skillet, and cook until softened, about 3-4 minutes.",
      "Stir in zucchini and cook for 2 minutes.",
      "Add cooked rice, diced tomatoes, tomato paste, Italian seasoning, cumin, beef broth, half the cheese, and parsley. Season with salt and pepper. Stir to combine and cook for 2-3 minutes.",
      "Spoon the mixture into the bell peppers. Cover the dish with foil.",
      "Bake for 30 minutes. Remove foil, sprinkle with remaining cheese, and bake for an additional 10 minutes until cheese is melted and peppers are tender.",
      "Garnish with additional parsley before serving."
    ],
    notes: "For a vegetarian version, substitute the ground beef with cooked lentils or a plant-based meat alternative. You can use any color bell peppers you prefer.",
    tags: ["dinner", "stuffed peppers", "beef", "family meals", "make ahead"]
  },
  {
    id: "d7",
    title: "Vegetable Curry",
    description: "A flavorful and aromatic vegetable curry that's both comforting and healthy.",
    image: "https://images.unsplash.com/photo-1604671568035-50412484ac2a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1752&q=80",
    category: "Dinner",
    prepTime: "15 minutes",
    cookTime: "30 minutes",
    totalTime: "45 minutes",
    servings: 6,
    calories: 310,
    ingredients: [
      "2 tablespoons vegetable oil",
      "1 onion, diced",
      "3 cloves garlic, minced",
      "1 tablespoon ginger, grated",
      "2 tablespoons curry powder",
      "1 teaspoon turmeric",
      "1 teaspoon cumin",
      "1/2 teaspoon coriander",
      "1/4 teaspoon cayenne pepper (adjust to taste)",
      "1 sweet potato, peeled and diced",
      "1 cauliflower, cut into florets",
      "2 carrots, sliced",
      "1 bell pepper, diced",
      "1 can (15 oz) chickpeas, drained and rinsed",
      "1 can (14.5 oz) diced tomatoes",
      "1 can (14 oz) coconut milk",
      "1 cup vegetable broth",
      "2 cups spinach, chopped",
      "Fresh cilantro for garnish",
      "Cooked rice or naan bread for serving"
    ],
    instructions: [
      "Heat oil in a large pot over medium heat. Add onion and cook until softened, about 5 minutes.",
      "Add garlic and ginger, and cook for 1 minute until fragrant.",
      "Stir in curry powder, turmeric, cumin, coriander, and cayenne pepper. Cook for 1 minute to toast the spices.",
      "Add sweet potato, cauliflower, carrots, and bell pepper. Stir to coat in the spices.",
      "Add chickpeas, diced tomatoes, coconut milk, and vegetable broth. Stir to combine.",
      "Bring to a boil, then reduce heat to low. Cover and simmer for 20-25 minutes until vegetables are tender.",
      "Stir in spinach and cook for 2-3 minutes until wilted.",
      "Taste and adjust seasoning as needed.",
      "Serve over rice or with naan bread, garnished with fresh cilantro."
    ],
    notes: "This curry is very versatile. Feel free to substitute vegetables based on what you have available. For extra protein, add cubed tofu or cooked chicken.",
    tags: ["dinner", "curry", "vegetarian", "vegan", "indian", "healthy"]
  },

  // Dessert Recipes (first from original data)
  {
    id: "2",
    title: "Classic Chocolate Chip Cookies",
    description: "Perfectly soft and chewy chocolate chip cookies that will satisfy any sweet tooth.",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
    category: "Desserts",
    prepTime: "15 minutes",
    cookTime: "12 minutes",
    totalTime: "27 minutes",
    servings: 24,
    calories: 180,
    ingredients: [
      "1 cup unsalted butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup brown sugar, packed",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "2 1/4 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "2 cups semi-sweet chocolate chips"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper.",
      "In a large bowl, cream together butter, granulated sugar, and brown sugar until light and fluffy.",
      "Beat in eggs one at a time, then stir in vanilla.",
      "In a separate bowl, combine flour, baking soda, and salt. Gradually add to the wet ingredients and mix until just combined.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons of dough onto prepared baking sheets.",
      "Bake for 10-12 minutes until edges are golden. Centers may look slightly underdone.",
      "Allow cookies to cool on baking sheet for 5 minutes before transferring to a wire rack."
    ],
    notes: "For extra flavor, try adding 1/2 cup of chopped nuts or using a mix of chocolate chips and chunks.",
    tags: ["cookies", "dessert", "baking", "chocolate"]
  },
  // Additional Dessert Recipes
  {
    id: "ds1",
    title: "Strawberry Cheesecake",
    description: "Creamy cheesecake with a graham cracker crust and fresh strawberry topping.",
    image: "https://images.unsplash.com/photo-1611293388250-580b08c4a145?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1738&q=80",
    category: "Desserts",
    prepTime: "30 minutes",
    cookTime: "50 minutes",
    totalTime: "8 hours (including chilling)",
    servings: 12,
    calories: 420,
    ingredients: [
      "For the crust:",
      "2 cups graham cracker crumbs",
      "1/3 cup granulated sugar",
      "1/2 cup unsalted butter, melted",
      "For the filling:",
      "4 packages (8 oz each) cream cheese, softened",
      "1 1/4 cups granulated sugar",
      "1/2 cup sour cream",
      "2 teaspoons vanilla extract",
      "4 large eggs",
      "For the topping:",
      "2 cups fresh strawberries, hulled and sliced",
      "1/4 cup granulated sugar",
      "1 tablespoon lemon juice",
      "1 teaspoon cornstarch mixed with 1 tablespoon water"
    ],
    instructions: [
      "Preheat oven to 325°F (165°C). Grease a 9-inch springform pan.",
      "In a bowl, mix graham cracker crumbs, sugar, and melted butter until evenly moistened. Press mixture into the bottom and 1 inch up the sides of the prepared pan.",
      "Bake crust for 10 minutes, then set aside to cool.",
      "In a large bowl, beat cream cheese until smooth. Gradually add sugar and mix until creamy.",
      "Blend in sour cream and vanilla.",
      "Add eggs one at a time, mixing on low speed just until each is incorporated. Do not overmix.",
      "Pour filling over the crust and smooth the top.",
      "Bake for 45-50 minutes until the center is almost set but still slightly jiggly.",
      "Turn off the oven, crack the door open, and let the cheesecake cool in the oven for 1 hour.",
      "Remove from oven and run a knife around the edge of the pan to loosen. Cool completely at room temperature.",
      "Refrigerate for at least 6 hours or overnight.",
      "For the topping, combine strawberries, sugar, and lemon juice in a saucepan. Cook over medium heat for 5 minutes.",
      "Add cornstarch mixture and cook for 1 minute until thickened. Cool completely.",
      "Before serving, spoon strawberry topping over the cheesecake."
    ],
    notes: "To prevent cracks, avoid overmixing the batter and don't open the oven door during baking. A water bath can also help maintain even baking temperature.",
    tags: ["dessert", "cheesecake", "strawberry", "baking", "special occasion"]
  },
  {
    id: "ds2",
    title: "Apple Crisp",
    description: "Warm spiced apples topped with a crispy oat and brown sugar streusel.",
    image: "https://images.unsplash.com/photo-1568571780765-9276230010a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1752&q=80",
    category: "Desserts",
    prepTime: "20 minutes",
    cookTime: "40 minutes",
    totalTime: "1 hour",
    servings: 8,
    calories: 320,
    ingredients: [
      "6 large apples, peeled, cored, and sliced",
      "1/2 cup granulated sugar",
      "1 tablespoon lemon juice",
      "1 teaspoon cinnamon",
      "1/4 teaspoon nutmeg",
      "For the topping:",
      "1 cup old-fashioned oats",
      "1 cup all-purpose flour",
      "1 cup brown sugar, packed",
      "1/2 teaspoon cinnamon",
      "1/4 teaspoon salt",
      "1/2 cup cold unsalted butter, cubed",
      "Vanilla ice cream for serving (optional)"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Grease a 9x13 inch baking dish.",
      "In a large bowl, toss apple slices with granulated sugar, lemon juice, cinnamon, and nutmeg until coated.",
      "Spread apple mixture in the prepared baking dish.",
      "In another bowl, combine oats, flour, brown sugar, cinnamon, and salt.",
      "Using a pastry cutter or your fingers, cut in cold butter until mixture resembles coarse crumbs.",
      "Sprinkle topping evenly over the apples.",
      "Bake for 35-40 minutes until topping is golden brown and apples are tender.",
      "Allow to cool slightly before serving.",
      "Serve warm with vanilla ice cream if desired."
    ],
    notes: "Use a mix of apple varieties for the best flavor. Granny Smith, Honeycrisp, and Gala work well together. The crisp can be reheated in a 350°F oven for 15 minutes.",
    tags: ["dessert", "apple", "crisp", "fall", "easy"]
  },
  {
    id: "ds3",
    title: "Chocolate Lava Cake",
    description: "Decadent individual chocolate cakes with a molten chocolate center.",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    category: "Desserts",
    prepTime: "15 minutes",
    cookTime: "14 minutes",
    totalTime: "29 minutes",
    servings: 4,
    calories: 380,
    ingredients: [
      "1/2 cup unsalted butter",
      "4 oz dark chocolate, chopped",
      "1 cup powdered sugar",
      "2 large eggs",
      "2 large egg yolks",
      "1 teaspoon vanilla extract",
      "1/3 cup all-purpose flour",
      "1/8 teaspoon salt",
      "Powdered sugar for dusting",
      "Fresh berries for serving (optional)"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Grease and lightly flour four 6-oz ramekins or custard cups.",
      "In a microwave-safe bowl, melt butter and chocolate together in 30-second intervals, stirring after each, until smooth.",
      "Whisk in powdered sugar until well blended.",
      "Add eggs and egg yolks, one at a time, whisking well after each addition.",
      "Stir in vanilla extract.",
      "Gently fold in flour and salt until just combined.",
      "Divide batter evenly among prepared ramekins.",
      "Place ramekins on a baking sheet and bake for 12-14 minutes until sides are firm but centers are still soft.",
      "Let stand for 1 minute.",
      "Run a knife around the edges to loosen, then invert onto serving plates.",
      "Dust with powdered sugar and serve immediately with fresh berries if desired."
    ],
    notes: "The key to perfect lava cakes is not overbaking them. The centers should still be molten when you remove them from the oven. You can prepare the batter ahead and refrigerate in the ramekins, then add 1-2 minutes to the baking time.",
    tags: ["dessert", "chocolate", "lava cake", "date night", "special occasion"]
  },
  {
    id: "ds4",
    title: "Key Lime Pie",
    description: "Tangy and sweet key lime pie with a graham cracker crust and whipped cream topping.",
    image: "https://images.unsplash.com/photo-1519915028121-7d3463d5b1ff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1887&q=80",
    category: "Desserts",
    prepTime: "20 minutes",
    cookTime: "15 minutes",
    totalTime: "3 hours (including chilling)",
    servings: 8,
    calories: 350,
    ingredients: [
      "For the crust:",
      "1 1/2 cups graham cracker crumbs",
      "1/3 cup granulated sugar",
      "6 tablespoons unsalted butter, melted",
      "For the filling:",
      "4 large egg yolks",
      "1 can (14 oz) sweetened condensed milk",
      "1/2 cup key lime juice (fresh or bottled)",
      "1 tablespoon lime zest",
      "For the topping:",
      "1 cup heavy cream",
      "2 tablespoons powdered sugar",
      "1/2 teaspoon vanilla extract",
      "Lime slices for garnish"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "In a bowl, combine graham cracker crumbs, sugar, and melted butter until evenly moistened.",
      "Press mixture into the bottom and sides of a 9-inch pie plate.",
      "Bake crust for 8 minutes, then set aside to cool.",
      "In a medium bowl, whisk egg yolks until pale and fluffy.",
      "Gradually whisk in sweetened condensed milk.",
      "Add lime juice and zest, and whisk until well combined.",
      "Pour filling into the cooled crust.",
      "Bake for 15 minutes until set but still slightly jiggly in the center.",
      "Cool completely at room temperature, then refrigerate for at least 2 hours or overnight.",
      "Before serving, whip heavy cream with powdered sugar and vanilla until stiff peaks form.",
      "Top pie with whipped cream and garnish with lime slices."
    ],
    notes: "If you can't find key limes, regular limes work well too. For best flavor, use fresh lime juice rather than bottled when possible.",
    tags: ["dessert", "pie", "key lime", "citrus", "summer"]
  },
  {
    id: "ds5",
    title: "Tiramisu",
    description: "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream.",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80",
    category: "Desserts",
    prepTime: "30 minutes",
    cookTime: "0 minutes",
    totalTime: "6 hours (including chilling)",
    servings: 12,
    calories: 380,
    ingredients: [
      "6 large egg yolks",
      "3/4 cup granulated sugar",
      "2/3 cup milk",
      "1 pound (16 oz) mascarpone cheese, room temperature",
      "1 1/2 cups heavy cream",
      "1 teaspoon vanilla extract",
      "1 1/2 cups strong brewed coffee, cooled",
      "1/4 cup coffee liqueur (like Kahlúa)",
      "2 packages (7 oz each) ladyfinger cookies",
      "1/4 cup unsweetened cocoa powder",
      "Chocolate shavings for garnish (optional)"
    ],
    instructions: [
      "In a heatproof bowl set over a pot of simmering water (double boiler), whisk egg yolks and sugar until pale and doubled in volume, about 5 minutes.",
      "Remove from heat and whisk in milk. Return to heat and cook, stirring constantly, until mixture thickens slightly and reaches 160°F (71°C).",
      "Remove from heat and let cool to room temperature.",
      "In a large bowl, beat mascarpone until smooth. Fold in the cooled egg mixture until well combined.",
      "In another bowl, whip heavy cream and vanilla until stiff peaks form. Gently fold into the mascarpone mixture.",
      "In a shallow dish, combine coffee and coffee liqueur.",
      "Quickly dip half of the ladyfingers in the coffee mixture (don't soak them) and arrange in a single layer in a 9x13 inch baking dish.",
      "Spread half of the mascarpone mixture over the ladyfingers.",
      "Repeat with remaining ladyfingers and mascarpone mixture.",
      "Dust the top with cocoa powder.",
      "Cover and refrigerate for at least 6 hours or overnight.",
      "Before serving, garnish with chocolate shavings if desired."
    ],
    notes: "The egg yolks in this recipe are cooked to a safe temperature. If you prefer, you can use pasteurized eggs. For a non-alcoholic version, omit the coffee liqueur and use additional coffee.",
    tags: ["dessert", "italian", "tiramisu", "coffee", "special occasion"]
  },
  {
    id: "ds6",
    title: "Vanilla Bean Crème Brûlée",
    description: "Smooth, rich vanilla custard with a crackling caramelized sugar topping.",
    image: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    category: "Desserts",
    prepTime: "20 minutes",
    cookTime: "45 minutes",
    totalTime: "3 hours (including chilling)",
    servings: 6,
    calories: 400,
    ingredients: [
      "2 cups heavy cream",
      "1 vanilla bean, split lengthwise, seeds scraped",
      "5 large egg yolks",
      "1/2 cup granulated sugar, plus more for topping",
      "1/4 teaspoon salt",
      "Fresh berries for serving (optional)"
    ],
    instructions: [
      "Preheat oven to 325°F (165°C). Place 6 ramekins in a large baking dish.",
      "In a saucepan over medium heat, combine cream, vanilla bean, and vanilla seeds. Heat until small bubbles form around the edges (do not boil). Remove from heat and let steep for 15 minutes.",
      "In a bowl, whisk together egg yolks, sugar, and salt until pale and smooth.",
      "Remove vanilla bean from cream. Gradually whisk the warm cream into the egg mixture.",
      "Strain the custard through a fine-mesh sieve into a liquid measuring cup.",
      "Divide custard among the ramekins.",
      "Pour hot water into the baking dish around the ramekins, creating a water bath that comes halfway up the sides of the ramekins.",
      "Bake for 35-45 minutes until custards are set but still slightly jiggly in the center.",
      "Remove ramekins from water bath and cool to room temperature.",
      "Cover and refrigerate for at least 2 hours or up to 3 days.",
      "Just before serving, sprinkle 1-2 teaspoons of sugar evenly over each custard.",
      "Use a kitchen torch to caramelize the sugar until melted and golden brown. Alternatively, place under a broiler for 2-3 minutes, watching carefully.",
      "Let stand for 1-2 minutes until sugar hardens, then serve with fresh berries if desired."
    ],
    notes: "If you don't have a vanilla bean, substitute with 1 tablespoon of vanilla extract added after removing the cream from heat. The caramelized sugar topping is best when freshly made, so wait to brûlée the tops until just before serving.",
    tags: ["dessert", "creme brulee", "french", "vanilla", "special occasion"]
  },
  {
    id: "ds7",
    title: "Banana Bread",
    description: "Moist and flavorful banana bread with walnuts - perfect for breakfast or dessert.",
    image: "https://images.unsplash.com/photo-1605190557072-8ebf954af4c8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1750&q=80",
    category: "Desserts",
    prepTime: "15 minutes",
    cookTime: "60 minutes",
    totalTime: "1 hour 15 minutes",
    servings: 10,
    calories: 280,
    ingredients: [
      "1/2 cup unsalted butter, softened",
      "1 cup granulated sugar",
      "2 large eggs",
      "3 ripe bananas, mashed",
      "1/4 cup milk",
      "1 teaspoon vanilla extract",
      "2 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "1/2 teaspoon cinnamon",
      "1/2 cup chopped walnuts, plus more for topping",
      "1 tablespoon brown sugar for topping (optional)"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Grease and flour a 9x5 inch loaf pan.",
      "In a large bowl, cream together butter and sugar until light and fluffy.",
      "Beat in eggs one at a time, then stir in mashed bananas, milk, and vanilla.",
      "In a separate bowl, whisk together flour, baking soda, salt, and cinnamon.",
      "Gradually add dry ingredients to the wet ingredients, mixing just until combined. Do not overmix.",
      "Fold in chopped walnuts.",
      "Pour batter into the prepared loaf pan. Sprinkle additional walnuts and brown sugar on top if desired.",
      "Bake for 60-65 minutes until a toothpick inserted in the center comes out clean.",
      "Cool in the pan for 10 minutes, then remove to a wire rack to cool completely."
    ],
    notes: "Use very ripe bananas with black spots for the best flavor. If your bananas aren't ripe enough, place them in a 300°F oven for 15-20 minutes until the skins turn black. For a variation, add 1/2 cup chocolate chips or dried cranberries.",
    tags: ["dessert", "banana bread", "baking", "breakfast", "make ahead"]
  },
  {
    id: "ds8",
    title: "Peach Cobbler",
    description: "Sweet peaches topped with a buttery, cake-like batter - a classic Southern dessert.",
    image: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80",
    category: "Desserts",
    prepTime: "15 minutes",
    cookTime: "45 minutes",
    totalTime: "1 hour",
    servings: 8,
    calories: 340,
    ingredients: [
      "For the filling:",
      "8 ripe peaches, peeled, pitted, and sliced",
      "1/2 cup granulated sugar",
      "1/4 cup brown sugar",
      "1/4 teaspoon cinnamon",
      "1/8 teaspoon nutmeg",
      "1 teaspoon lemon juice",
      "2 teaspoons cornstarch",
      "For the batter:",
      "1 cup all-purpose flour",
      "1 cup granulated sugar",
      "1 teaspoon baking powder",
      "1/2 teaspoon salt",
      "1/2 cup unsalted butter, melted",
      "1 teaspoon vanilla extract",
      "1/4 cup hot water",
      "Vanilla ice cream for serving (optional)"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "In a large bowl, combine sliced peaches, 1/2 cup granulated sugar, brown sugar, cinnamon, nutmeg, lemon juice, and cornstarch. Toss to coat peaches evenly.",
      "Pour peach mixture into a 2-quart baking dish or 9x9 inch square pan.",
      "In a separate bowl, whisk together flour, 1 cup granulated sugar, baking powder, and salt.",
      "Add melted butter and vanilla. Stir until mixture resembles coarse crumbs.",
      "Sprinkle the batter evenly over the peaches.",
      "Pour hot water over the top of the batter. Do not stir.",
      "Bake for 40-45 minutes until the top is golden brown and the filling is bubbly.",
      "Let cool for 15 minutes before serving.",
      "Serve warm with vanilla ice cream if desired."
    ],
    notes: "If fresh peaches aren't available, you can use frozen (thawed and drained) or canned peaches (drained). For canned peaches, reduce the sugar in the filling by half.",
    tags: ["dessert", "cobbler", "peach", "southern", "summer"]
  },
  {
    id: "ds9",
    title: "Lemon Bars",
    description: "Tangy lemon custard on a buttery shortbread crust, dusted with powdered sugar.",
    image: "https://images.unsplash.com/photo-1528252994753-470da8a0e8e6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1887&q=80",
    category: "Desserts",
    prepTime: "15 minutes",
    cookTime: "40 minutes",
    totalTime: "3 hours (including cooling)",
    servings: 16,
    calories: 210,
    ingredients: [
      "For the crust:",
      "1 cup unsalted butter, softened",
      "1/2 cup granulated sugar",
      "2 cups all-purpose flour",
      "1/4 teaspoon salt",
      "For the filling:",
      "2 cups granulated sugar",
      "1/3 cup all-purpose flour",
      "1 teaspoon lemon zest",
      "6 large eggs",
      "1 cup fresh lemon juice (about 4-5 lemons)",
      "Powdered sugar for dusting"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Line a 9x13 inch baking pan with parchment paper.",
      "For the crust, in a large bowl, cream together butter and sugar until light and fluffy.",
      "Add flour and salt, and mix until dough forms.",
      "Press dough evenly into the bottom of the prepared pan.",
      "Bake crust for 15-20 minutes until lightly golden.",
      "While crust is baking, prepare the filling: In a bowl, whisk together sugar, flour, and lemon zest.",
      "Add eggs and lemon juice, and whisk until well combined.",
      "Pour filling over the hot crust when it comes out of the oven.",
      "Return to oven and bake for 20-25 minutes until filling is set.",
      "Cool completely in the pan on a wire rack.",
      "Once cooled, refrigerate for at least 2 hours.",
      "Cut into bars and dust with powdered sugar just before serving."
    ],
    notes: "The lemon bars will keep in an airtight container in the refrigerator for up to 4 days. Add a layer of parchment paper between layers if stacking.",
    tags: ["dessert", "lemon", "bars", "citrus", "spring"]
  }
];

export const categories = [
  { id: "breakfast", name: "Breakfast", count: 10 },
  { id: "lunch", name: "Lunch", count: 10 },
  { id: "dinner", name: "Dinner", count: 10 },
  { id: "desserts", name: "Desserts", count: 10 },
  { id: "vegan", name: "Vegan", count: 2 }
];

export const getRecipesByCategory = (categoryId: string): Recipe[] => {
  return recipes.filter(recipe => 
    recipe.category.toLowerCase() === categoryId.toLowerCase() ||
    recipe.tags.includes(categoryId.toLowerCase())
  );
};

export const getRelatedRecipes = (recipeId: string, limit = 3): Recipe[] => {
  const currentRecipe = recipes.find(r => r.id === recipeId);
  if (!currentRecipe) return [];
  
  // Find recipes with similar tags or category
  return recipes
    .filter(recipe => 
      recipe.id !== recipeId && (
        recipe.category === currentRecipe.category ||
        recipe.tags.some(tag => currentRecipe.tags.includes(tag))
      )
    )
    .slice(0, limit);
};

// For the recipes page implementation
export const paginateRecipes = (
  recipes: Recipe[], 
  page: number, 
  perPage: number = 6
) => {
  const startIndex = (page - 1) * perPage;
  const endIndex = startIndex + perPage;
  const paginatedRecipes = recipes.slice(startIndex, endIndex);
  const totalPages = Math.ceil(recipes.length / perPage);
  
  return {
    recipes: paginatedRecipes,
    totalPages,
    currentPage: page
  };
};
